#!/usr/bin/env bash

set -euo pipefail

#%include out.sh
#%include isroot.sh

#%include configuration.sh

isroot:require "You must be root to run the updater job"

cd "$PUP_gitdir"

bin/pupdater >/dev/null 2>&1
