#!/usr/bin/env bash

set -euo pipefail

#%include std/out.sh
#%include std/isroot.sh
#%include std/readkv.sh

#%include configuration.sh

isroot:require "You must be root to run the updater"

check_config_file() {
    if [[ ! -f "$PUP_conf" ]]; then
        out:fail "No configuration file !"
    fi
}

run_update_scripts() {
    for runscript in $(find scripts/ -executable|tail -n +2 | sort ); do
        echo "$thedate" >> "$PUP_logfile"
        "$runscript" >> "$PUP_logfile" || {
            cat "$PUP_logfile"| mailx -s "[$runscript] on $machinename FAILED" $alertemail
            if [[ "$updatemode" = "blocking" ]]; then
                exit 2
            fi
        }
    done
}

main() {
    check_config_file

    thedate="$(date "+%F%T"|sed -r 's/[^0-9]+//g')"
    alertemail="$(readkv email "$PUP_conf")"
    machinename="$(readkv machine "$PUP_conf")"
    updatemode="$(readkv update_mode "$PUP_conf")"

    cd "$PUP_gitdir"

    git pull origin master || {
        echo ""|mailx -s "Failed to pull update automation on $machinename" $alertemail
        exit 127
    }

}

main "$@"
